# permissions for end users to view kubeanchors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeanchor-viewer-role
rules:
- apiGroups:
  - core.operator.kube-anchor.co
  resources:
  - kubeanchors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.operator.kube-anchor.co
  resources:
  - kubeanchors/status
  verbs:
  - get
